apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-claim
  labels:
    app: nginx-app      
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi

