apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-pod
  name: nginx-pod        
spec:
  containers:
  - image: nginx:1.14.0
    name: web-server
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes: 
  - name: data 
    gitRepo:
      repository: https://github.com/kolomyya/Simple-Website.git
      revision: master
      directory: . 
